# Generated by Django 4.2.16 on 2025-01-10 13:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ReviewPay_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='BusinessVerifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ACN', models.CharField(max_length=255)),
                ('business_web', models.CharField(max_length=255)),
                ('fullname_director_1', models.CharField(max_length=255)),
                ('fullname_director_2', models.CharField(max_length=255)),
                ('admin_phone_number', models.CharField(max_length=255)),
                ('business_phone_number', models.CharField(max_length=255)),
                ('facebook_link', models.CharField(max_length=255)),
                ('instra_link', models.CharField(max_length=255)),
                ('admin_email', models.CharField(max_length=255)),
                ('client_email', models.CharField(max_length=255)),
                ('openning_hours', models.CharField(max_length=255)),
                ('government_issue_document', models.ImageField(upload_to='verification_business/')),
                ('business_name_evidence', models.ImageField(upload_to='verification_business/')),
                ('company_extract_issue', models.ImageField(upload_to='verification_business/')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Business Verification',
                'verbose_name_plural': 'Business Verifications',
            },
        ),
    ]
