# Generated by Django 4.2.16 on 2024-11-12 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReviewPay_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryusers',
            name='business_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
