# Generated by Django 4.2.16 on 2025-01-03 14:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ReviewPay_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoryusers',
            name='abn_number',
        ),
        migrations.RemoveField(
            model_name='categoryusers',
            name='business_address',
        ),
        migrations.RemoveField(
            model_name='categoryusers',
            name='business_name',
        ),
        migrations.RemoveField(
            model_name='categoryusers',
            name='category',
        ),
        migrations.RemoveField(
            model_name='categoryusers',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='categoryusers',
            name='sub_category',
        ),
        migrations.AlterField(
            model_name='categoryusers',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='categoryusers',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('business', 'Business User')], default='admin user', max_length=10),
        ),
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.TextField()),
                ('gender', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Detail',
                'verbose_name_plural': 'User Details',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('product_description', models.TextField()),
                ('product_price', models.CharField(max_length=255)),
                ('product_images', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Products Details',
                'verbose_name_plural': 'Products Details',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=255)),
                ('identification_number', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('employee_email_address', models.EmailField(max_length=254)),
                ('working_since', models.CharField(max_length=100)),
                ('employee_profiles', models.ImageField(blank=True, null=True, upload_to='employee_profiles/')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Employee Detail',
                'verbose_name_plural': 'Employees Details',
            },
        ),
        migrations.CreateModel(
            name='Businessdetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('businessLogo', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('sub_category', models.CharField(blank=True, max_length=100, null=True)),
                ('abn_number', models.CharField(blank=True, max_length=20, null=True)),
                ('business_name', models.CharField(blank=True, max_length=100, null=True)),
                ('business_address', models.TextField(blank=True, null=True)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='businesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Business Detail',
                'verbose_name_plural': 'Business Details',
            },
        ),
    ]
