# Generated by Django 4.2.16 on 2025-03-11 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReviewPay_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessdetail',
            name='marchant_api_key',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
