# Generated by Django 4.2.16 on 2025-01-24 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReviewPay_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommingsoonLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(default=0, max_length=254)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
            ],
        ),
    ]
