# Generated by Django 4.2.16 on 2025-01-10 14:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ReviewPay_app', '0002_alter_feedback_business_businessverifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessverifications',
            name='business',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='category', to=settings.AUTH_USER_MODEL),
        ),
    ]
