# Generated by Django 4.2.16 on 2025-03-12 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReviewPay_app', '0002_alter_businessdetail_marchant_api_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adv_sub', models.CharField(max_length=100)),
                ('adv_sub2', models.CharField(blank=True, max_length=100, null=True)),
                ('adv_sub3', models.PositiveIntegerField(blank=True, null=True)),
                ('adv_sub4', models.CharField(blank=True, max_length=100, null=True)),
                ('adv_sub5', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('transaction_id', models.CharField(max_length=30, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('user_id', models.CharField(max_length=100)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
