# Generated by Django 4.2.16 on 2025-01-24 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReviewPay_app', '0002_commingsoonlogin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commingsoonlogin',
            options={'verbose_name': 'CommingsoonLogin', 'verbose_name_plural': 'CommingsoonLogin'},
        ),
        migrations.AlterField(
            model_name='commingsoonlogin',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
    ]
