# Generated by Django 4.2.16 on 2025-03-12 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReviewPay_app', '0003_ordertracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordertracking',
            name='sub_category',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
