# Generated by Django 4.2.16 on 2025-02-03 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ReviewPay_app', '0003_alter_commingsoonlogin_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessdetail',
            name='businessLogo',
        ),
        migrations.CreateModel(
            name='BusinessLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to='business_logo//')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_logo', to='ReviewPay_app.businessdetail')),
            ],
        ),
    ]
