# Generated by Django 4.2.16 on 2025-01-11 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReviewPay_app', '0003_alter_businessverifications_business'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('quality', models.IntegerField(default=0)),
                ('performance', models.IntegerField(default=0)),
                ('easy_to_use', models.IntegerField(default=0)),
                ('durability', models.IntegerField(default=0)),
            ],
        ),
    ]
