# Generated by Django 4.2.16 on 2024-11-21 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReviewPay_app', '0003_rename_profile_picture_categoryusers_businesslogo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_price',
            field=models.CharField(max_length=255),
        ),
    ]
