# Generated by Django 4.2.16 on 2025-01-11 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ReviewPay_app', '0004_productevaluation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductEvaluation',
            new_name='BusinessStates',
        ),
    ]
