# Generated by Django 4.2.16 on 2025-03-12 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ReviewPay_app', '0004_ordertracking_sub_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordertracking',
            old_name='sub_category',
            new_name='marchant_api',
        ),
    ]
