# Generated by Django 4.2.16 on 2024-12-24 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ReviewPay_app', '0005_emailvalidation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailValidation',
        ),
    ]
