# Generated by Django 4.2.16 on 2025-03-12 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReviewPay_app', '0005_rename_sub_category_ordertracking_marchant_api'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordertracking',
            name='transaction_id',
            field=models.CharField(max_length=30),
        ),
    ]
