# Generated by Django 4.2.16 on 2025-02-03 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ReviewPay_app', '0005_referralcashback_reviewcashback'),
    ]

    operations = [
        migrations.AddField(
            model_name='referralcashback',
            name='business',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ReferralCashback', to='ReviewPay_app.businessdetail'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reviewcashback',
            name='business',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ReviewCashback', to='ReviewPay_app.businessdetail'),
            preserve_default=False,
        ),
    ]
