# Generated by Django 4.2.16 on 2025-04-04 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReviewPay_app', '0006_alter_ordertracking_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessdetail',
            name='qr_code',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
