# Generated by Django 4.2.16 on 2025-01-10 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ReviewPay_app', '0006_remove_product_product_images_productimage_barcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barcode',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barcode', to='ReviewPay_app.product'),
        ),
    ]
