# Generated by Django 4.2.16 on 2025-01-13 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReviewPay_app', '0006_rename_businessstates_businessstate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessverifications',
            name='business_name_evidence',
            field=models.ImageField(upload_to='verification_business_business_name_evidence'),
        ),
        migrations.AlterField(
            model_name='businessverifications',
            name='company_extract_issue',
            field=models.ImageField(upload_to='verification_business_company_extract_issue'),
        ),
        migrations.AlterField(
            model_name='businessverifications',
            name='government_issue_document',
            field=models.ImageField(upload_to='verification_business_government_issue_document/'),
        ),
    ]
