# Generated by Django 4.2.16 on 2025-01-13 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReviewPay_app', '0007_alter_businessverifications_business_name_evidence_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessdetail',
            name='businessLogo',
            field=models.ImageField(blank=True, null=True, upload_to='business_logo/'),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='user_images/'),
        ),
    ]
