# Generated by Django 4.2.16 on 2024-12-28 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReviewPay_app', '0007_remove_product_business_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryusers',
            name='name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
