# Generated by Django 4.2.16 on 2025-02-06 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ReviewPay_app', '0007_usercashback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercashback',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usercashback', to='ReviewPay_app.userdetail'),
        ),
    ]
