# Generated by Django 4.2.16 on 2025-04-07 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReviewPay_app', '0010_qrscan_delete_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessdetail',
            name='business_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
