# Generated by Django 4.2.16 on 2025-04-11 11:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ReviewPay_app', '0011_businessdetail_business_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_detail', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('delay', 'Delay')], default='pending', max_length=10)),
                ('business_detail_date', models.DateField()),
                ('product_image', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('delay', 'Delay')], default='pending', max_length=10)),
                ('product_image_date', models.DateField()),
                ('business_verify', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('delay', 'Delay')], default='pending', max_length=10)),
                ('business_verify_date', models.DateField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
