# Generated by Django 4.2.16 on 2025-04-11 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReviewPay_app', '0012_notifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='business_detail_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='business_verify_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='product_image_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
