# Generated by Django 4.2.16 on 2025-04-22 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReviewPay_app', '0014_userdetail_email_userdetail_phone_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Welcome_new_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
