# Generated by Django 4.2.16 on 2025-04-22 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ReviewPay_app', '0015_welcome_new_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='favorate_business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='ReviewPay_app.businessdetail')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_businesses', to='ReviewPay_app.userdetail')),
            ],
            options={
                'unique_together': {('user', 'business')},
            },
        ),
    ]
