# Generated by Django 4.2.16 on 2025-04-22 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ReviewPay_app', '0016_favorate_business'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessdetail',
            name='business_url',
        ),
    ]
