# Generated by Django 4.2.16 on 2025-04-24 13:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ReviewPay_app', '0018_welcome_new_user_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_business_invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_service', models.CharField(max_length=100)),
                ('invoice_ammount', models.CharField(max_length=100)),
                ('reviewcashback', models.CharField(max_length=100)),
                ('refferial_code', models.CharField(max_length=100)),
                ('client_name', models.CharField(max_length=100)),
                ('client_phone', models.CharField(max_length=100)),
                ('client_email', models.CharField(max_length=100)),
                ('proof_purchase', models.FileField(blank=True, null=True, upload_to='product_proof_purchase/')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_detail', to='ReviewPay_app.businessverifications')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
