# Generated by Django 4.2.16 on 2025-04-24 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ReviewPay_app', '0019_product_business_invoice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_business_invoice',
            old_name='user_id',
            new_name='user',
        ),
    ]
