# Generated by Django 4.2.16 on 2025-04-24 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ReviewPay_app', '0020_rename_user_id_product_business_invoice_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_business_invoice',
            old_name='invoice_ammount',
            new_name='invoice_amount',
        ),
    ]
