# Generated by Django 4.2.16 on 2025-04-25 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReviewPay_app', '0021_rename_invoice_ammount_product_business_invoice_invoice_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_business_invoice',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
