# Generated by Django 4.2.16 on 2025-04-25 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ReviewPay_app', '0023_productclientreview'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productclientreview',
            old_name='culture_one2one',
            new_name='culture_expertise',
        ),
        migrations.RenameField(
            model_name='productclientreview',
            old_name='operator_expertise',
            new_name='culture_extra_care',
        ),
    ]
