# Generated by Django 4.2.16 on 2025-04-25 13:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ReviewPay_app', '0024_rename_culture_one2one_productclientreview_culture_expertise_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productclientreview',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productclientreview',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
