# Generated by Django 4.2.16 on 2025-04-30 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ReviewPay_app', '0027_notification'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='notification',
            new_name='NotificationMassage',
        ),
    ]
