# Generated by Django 4.2.16 on 2025-05-13 08:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReviewPay_app', '0030_alter_usersession_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersession',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
