# Generated by Django 4.2.16 on 2025-05-16 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReviewPay_app', '0031_alter_usersession_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryusers',
            name='refferial_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
