# Generated by Django 4.2.16 on 2025-05-16 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReviewPay_app', '0032_categoryusers_refferial_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryusers',
            name='refferial_code',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
