# Generated by Django 4.2.16 on 2025-05-16 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReviewPay_app', '0033_alter_categoryusers_refferial_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoryusers',
            name='refferial_code',
        ),
        migrations.AddField(
            model_name='categoryusers',
            name='referral_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
