# Generated by Django 4.2.16 on 2025-05-16 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReviewPay_app', '0034_remove_categoryusers_refferial_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='refferial_code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.CharField(max_length=255)),
                ('refferial_code', models.CharField(max_length=255)),
            ],
        ),
    ]
