# Generated by Django 4.2.16 on 2025-06-03 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReviewPay_app', '0035_refferial_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='profile_image_color',
            field=models.ImageField(blank=True, null=True, upload_to='user_images/'),
        ),
    ]
