# Generated by Django 4.2.16 on 2025-06-05 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReviewPay_app', '0036_userdetail_profile_image_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='profile_image_color',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
