# Generated by Django 4.2.16 on 2025-06-11 15:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ReviewPay_app', '0037_alter_userdetail_profile_image_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessdetail',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='businessdetail',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
