# Generated by Django 4.2.16 on 2025-07-07 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReviewPay_app', '0039_remove_notifications_product_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businessverifications',
            old_name='openning_hours',
            new_name='monday_from',
        ),
        migrations.AddField(
            model_name='businessverifications',
            name='friday_from',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='businessverifications',
            name='friday_to',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='businessverifications',
            name='monday_to',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='businessverifications',
            name='saturday_from',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='businessverifications',
            name='saturday_to',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='businessverifications',
            name='sunday_from',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='businessverifications',
            name='sunday_to',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='businessverifications',
            name='thursday_from',
            field=models.CharField(default=11, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='businessverifications',
            name='thursday_to',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='businessverifications',
            name='tuesday_from',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='businessverifications',
            name='tuesday_to',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='businessverifications',
            name='wednesday_from',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='businessverifications',
            name='wednesday_to',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
