# Generated by Django 4.2.16 on 2025-07-08 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReviewPay_app', '0040_rename_openning_hours_businessverifications_monday_from_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='industry_quesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indestry', models.TextField()),
                ('business_type', models.TextField()),
                ('metrix', models.TextField()),
                ('metrix_question', models.TextField()),
                ('metrix_category', models.TextField()),
                ('sector', models.TextField()),
            ],
        ),
    ]
