# Generated by Django 4.2.16 on 2025-07-08 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ReviewPay_app', '0041_industry_quesion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='industry_quesion',
            new_name='industry_question',
        ),
    ]
