# Generated by Django 4.2.16 on 2025-07-22 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReviewPay_app', '0042_rename_industry_quesion_industry_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessdetail',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product_business_invoice',
            name='invoice_number',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
